version: 2.1

workflows:

  docker-pull-test:
    jobs:
      - pull-test

jobs:
  pull-test:
    docker:
    - image: 'bitnami/postgresql:13.5.0'
    resource_class: small
    steps:
      - run: echo "test"
